import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

TextStyle treningKarticaTitleTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 20, fontWeight: FontWeight.w600));
TextStyle timeAndRepsTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[700]!, fontSize: 16, fontWeight: FontWeight.w400));
TextStyle workoutTimerDrawerTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 25, fontWeight: FontWeight.w600));
TextStyle drawerOptionTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 19, fontWeight: FontWeight.w500));
TextStyle textFieldRepsTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 19, fontWeight: FontWeight.w500,height: 1));
TextStyle textFieldImeTreningaTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 19, fontWeight: FontWeight.w500));
TextStyle textFieldImeVezbeTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 19, fontWeight: FontWeight.w500,height: 1.25));
TextStyle restSerijaKarticaTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 23, fontWeight: FontWeight.w500));
TextStyle appBarTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 25, fontWeight: FontWeight.bold));
TextStyle dialogTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 14, fontWeight: FontWeight.w600));
TextStyle grayDialogTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey, fontSize: 14, fontWeight: FontWeight.w600));
TextStyle dialogErrorTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.red[900]!, fontSize: 14, fontWeight: FontWeight.w500));
TextStyle trainingBottomButtonTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 13, fontWeight: FontWeight.bold));
TextStyle timerButtonTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 25, fontWeight: FontWeight.bold));
TextStyle invalidTimerButtonTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.red[900]!, fontSize: 25, fontWeight: FontWeight.bold));
TextStyle pokreniTreningNazivTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 23, fontWeight: FontWeight.w600, height: 0.8));
TextStyle pokreniTreningVremeTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 40, fontWeight: FontWeight.w300, height: 0.8));
TextStyle pokreniTreningVremeVelikoTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 90, fontWeight: FontWeight.w300, height: 0.8));
TextStyle pokreniTreningVremeMsTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 20, fontWeight: FontWeight.w400, height: 0.9));
TextStyle pokreniTreningVremeMsVelikoTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 55, fontWeight: FontWeight.w300, height: 0.9));
TextStyle pokreniTreningPonavljanjaTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 20, fontWeight: FontWeight.normal));
TextStyle popupMeniTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 14, fontWeight: FontWeight.normal));
TextStyle toggleSwitchTextStyle1 = GoogleFonts.poppins(textStyle: const TextStyle(color: Colors.white, fontSize: 14, fontWeight: FontWeight.normal));
TextStyle toggleSwitchTextStyle2 = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900], fontSize: 14, fontWeight: FontWeight.normal));
TextStyle startTimeTextStyle = GoogleFonts.poppins(textStyle: const TextStyle(color: Colors.white, fontSize: 240, fontWeight: FontWeight.w200, height: 0.8));
TextStyle pokreniButtonTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900], fontSize: 30, fontWeight: FontWeight.normal));
TextStyle pokreniAppBarButtonTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900], fontSize: 15, fontWeight: FontWeight.bold));
TextStyle vremeDoPocetkaTextStyle = GoogleFonts.poppins(textStyle: const TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.normal,height: 0.99));
TextStyle sTextStyle = GoogleFonts.poppins(textStyle: const TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.normal, height: 1));
TextStyle pokreniTreningSledeciTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900]!, fontSize: 15, fontWeight: FontWeight.w600));
TextStyle textFieldLabelTextStyle = GoogleFonts.poppins(textStyle: TextStyle(color: Colors.grey[900], fontSize: 14, fontWeight: FontWeight.normal));
